################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
- sections:
  - title: Getting Started
    link: docs/getting-started.md
    sections: 
  - title: VerifyNow Functions
    link: docs/verifynow-functions.md
  - title: VerifyNow Integration Guide
    link: docs/verifynow-integration-guide.md
  - title: VerifyNow Webservice API
    link: docs/verifynow-webserviceapi.md
  - title: CSS Integration
    link: docs/css-integration.md
  - title: accountverification
    sections: 
    - title: Account Verification Methods
      link: docs/accountverification/account-verification-methods.md
    - title: Account Verification Flows
      link: docs/accountverification/account-verification-flows.md
    - title: Automated Account Addition
      link: docs/accountverification/automated-account-additions.md
    - title: Real-Time Verification Addition(RTVA)
      link: docs/accountverification/realtime-verification-additions.md
  - title: Quick Summary On Account Verfication
    link: docs/quicksummary-onacctverification.md
  - title: Exit Points
    link: docs/exit-points.md
  - title: Account Verification Status
    link: docs/account-verification-status.md
  - title: Risk Controls
    link: docs/risk-controls.md
- sections:
  - title: Initial Token
    sections:
    - title: SSO Token
      link: docs/getting-started/sso-token.md
    - title: test
      link: docs/getting-started/uitest.md
