################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productionDescription: The VerifyNow product acts as a single integration for account verification before money movement. VerifyNow from Fiserv leverages proprietary and third-party data sources and account verification tools to help Financial Institutions (FIs), Government Agencies, Insurance Companies, Corporations, FinTech and other industries reduce fraud exposure in connection with funding new accounts, transferring funds, payment initiation, disbursements, and other use cases while meeting customer expectations through faster, real-time approvals.
  getStarted: /docs/getting-started.md
benefits:
  - title: Account User Verification
    description: Verify the authorized user and ownership of an account to reduce fraud prior to money movement.
  - title: Account Status Verification
    description: Verify the account status, and associated risk factors to minimize returns, either on its own or alongside ownership verification.
  - title: Real-Time Access
    description: VerifyNow offers multiple methods to enable instant verification, irrespective of the user sessions, to broaden account coverage, boost successful verifications, and minimize organisational risk.
featuredFeatures:
  - title: Identity Verification 
    groupName: 
    description: Identity   verification is critical to any fraud mitigation strategy. This facilitates enhanced real-time verification of funding account ownership by using a combination of multiple data sources and Fiserv proprietary verification methods.
    featured: false
    relatedDocs:
     - link: null
       title:
  - title: Account Ownership Verification
    groupName: Account Verification
    description:  VerifyNow performs real-time account verification by comparing data input to the system with data from the FIs that services the account. It can verify account status and ownership, with as little as routing and account numbers, and first and last names or business names.
    featured: true
    tags: ["tag1", "tag2"]
    relatedDocs:
      - relatedDoc: null
        title: Verify Accounts Using VerifyNow
        description: Verify Accounts Using VerifyNow
        link: docs/verifynow-account-verification-method.md
    relatedAPIs:
      - relatedAPI: null
        title: Verify NOW
        description: VerifyNow performs real-time account verification by comparing data input into the system by a user with data collected from the website of financial institutions that service the account.
        type: post
        path: /cashedgerws/verifynow/verify/v1
  - title: Seamless Integration
    groupName: Manage Account
    description:  VerifyNow is also available as a standalone solution that you may integrate with your existing online funding and/or money transfer solutions and is integrated with your enterprise application by way of an easy to integrate widget and/or REST API.
    featured: true
    relatedDocs:
     - link: null
       title: Account Verification
  - title: Diverse Data and Verification Methods
    groupName: Featured Offerings
    description: VerifyNow offers both passive and interactive account ownership, and status verification methods leveraging multiple data sources, including Fiserv proprietary data and Early Warning Services (EWS) contributed by FIs. Also integrated with the Fiserv AllData Aggregation service to provide account ownership through user-permissioned data.
    featured: true
    relatedDocs:
     - link: null
       title: Featured Offerings
  - title: Privacy Built-In
    groupName: Industry-Leading Security
    description: Customer data is never shared or sold to third parties. User credentials are never saved; only data that must be stored for regulatory compliance is retained.
    featured: true
    relatedDocs:
     - link: null
       title: Industry-Leading Security