################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productionDescription: Enhance your digital payment and transfer offerings, drive revenue and strengthen relationships by offering the flexibility to transfer funds to and from accounts at different Financial Institution (FI) with TransferNow. The Fiserv ePayments TransferNow product enables a FI to offer secure inter-institution funds transfer services. With TransferNow, customers can transfer money between accounts and debit cards.
  getStarted: /docs/getting-started.md
benefits:
  - title: Payment Account Verification
    description: Getting users quickly authenticated is easy when Fiserv helps verify the account provided is owned by the same person trying to initiate the ACH Transfer.
  - title: Real-time Access
    description: VerifyNow includes Early Warning Services® to enable instant verification. This increases verification success and happens completely behind the scenes.
  - title: Credit Decisions and Verification
    description: Data from third-party partnerships and from our extensive footprint in bank, merchant and card processing improves accuracy and helps reduce fraud.
featuredFeatures:
  - title: Multiple Transfer Speeds 
    groupName: 
    description: Give customers multiple transfer speed options from Standard ACH, and Next Day, to Next Day Good Funds or Instant.
    featured: true
    relatedDocs:
     - link: docs/fund-transfer/FT-freq.md
       title:
  - title: Real Time Speed using Instant Transfer
    groupName: Account Verification
    description: NOW® Network from Fiserv lets your accountholders transfer money between two instant-enabled accounts at different financial institutions in real-time or by the next day. This removes the credit risk related to ACH-based, next-day services.
    featured: true
    relatedDocs:
     - link: docs/acc-to-acc-transfer/Account-Verify/Instant-Verify.md
       title: Instant Verification
  - title: Multiple Account Verification
    groupName: Manage Account
    description: Fiserv offers several advanced alternatives to help you protect against online banking fraud. With Multifactor Authentication from Fiserv, you can enhance online security and maintain compliance with banking regulations without devoting significant resources.
    featured: true
    relatedDocs:
     - link: docs/acc-to-acc-transfer/Manage-Account/acc-verify-home.md
       title: Account Verification
  - title: Responsive Web Design 
    groupName: Responsive Web Design
    description: Having an interactive, innovative website is key to meeting customer expectations and keeping them interested in your brand. With Web Design Services, Fiserv offers flexible, responsive design for financial institutions delivering outstanding results for desktop, tablet and mobile users, ensuring a consistent brand experience across all devices. Benefits of our services include more mobile traffic, lower maintenance needs, faster webpages and an overall improved online experience.
    featured: false
    relatedDocs:
     - link: docs/resp-webdesign.md
       title: Responsive Web Design
  - title: Industry-Leading Security
    groupName: Industry-Leading Security
    description: Leverage Fiserv best -of-breed, powerful risk management tools.
    featured: false
    relatedDocs:
     - link: /docs/getting-started.md
       title: Industry-Leading Security