################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productionDescription: The VerifyNow™ product acts as a platform for account verification before providing access or allowing money to move. VerifyNow from Fiserv leverages proprietary and third-party account verification tools to help financial institutions (FI)s reduce fraud exposure in connection with funding new accounts and transferring funds directly to or from your online banking site safely and meet customer expectations through faster, real-time approvals.
  getStarted: /docs/getting-started.md
benefits:
  - title: Payment Account Verification
    description: Easy user authentication in verifying the accounts when the account holder initiates the ACH Transfer.
  - title: Real-Time Access
    description: VerifyNow includes EWS® to enable instant verification and increases successful verifications.
  - title: Credit Decisions and Verification
    description: Data from third-party partnerships improves accuracy and helps reduce fraud.
featuredFeatures:
  - title: Identity Verification 
    groupName: 
    description: Identity   verification is critical to any fraud mitigation strategy. This facilitates enhanced real-time verification of funding account ownership by using a combination of multiple data sources and Fiserv proprietary verification methods.
    featured: false
    relatedDocs:
     - link: null
       title:
  - title: Account Ownership Verification
    groupName: Account Verification
    description: VerifyNow performs real-time account verification by comparing data input into the system by a user with data collected from the website of financial institutions that service the account.
    featured: true
    tags: ["tag1", "tag2"]
    relatedDocs:
      - relatedDoc: null
        title: Verify Accounts Using VerifyNow
        description: Verify Accounts Using VerifyNow
        link: docs/verifynow-account-verification-method.md
    relatedAPIs:
      - relatedAPI: null
        title: Verify NOW
        description: VerifyNow performs real-time account verification by comparing data input into the system by a user with data collected from the website of financial institutions that service the account.
        type: post
        path: /cashedgerws/verifynow/verify/v1
  - title: Seamless Integration / Standalone Solution
    groupName: Manage Account
    description: VerifyNow is also available as a standalone solution that you may integrate with your existing online funding and/or money transfer solutions and is integrated with your enterprise application by way of an API.
    featured: true
    relatedDocs:
     - link: null
       title: Account Verification
  - title: EWS / ALLData Aggregation System 
    groupName: Responsive Web Design
    description: EWS houses data contributed by various FIs and uses this data to authenticate account ownership. AllData Aggregation via REST API helps to access consumer-permissioned data that can be used to develop solutions.
    featured: true
    relatedDocs:
     - link: null
       title: Responsive Web Design
  - title: Privacy Built-In
    groupName: Industry-Leading Security
    description: Customer data is never shared or sold to third parties. When a user ID is deleted, all data associated with that ID is also deleted; only data must be stored for regulatory compliance is retained.
    featured: true
    relatedDocs:
     - link: null
       title: Industry-Leading Security