################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productionDescription: With developer-friendly, flexible communication standards, unified APIs, and pre-certified integrations the Commerce Hub reduces development time and accelerates speed to market. A single entry point and intelligent orchestration layer creates a unified payments, reporting, and boarding experience through your existing infrastructure. With less ongoing maintenance and fewer operational costs, you can focus on creating new ways for consumers to discover and interact with your brand.
  getStarted: /docs/getting-started.md
benefits:
  - title: NOW Network
    description: NOW is an acronym for “Network for Our World,” and Fiserv recently introduced the NOW Gateway RTP Network, which can receive credit transfers from RTP.
  - title: Unmatched Presence
    description: Enable customers to move money to and from checking, savings and money market accounts at nearly every U.S.-based financial institution.
  - title: Optimized Operations
    description: Handle all aspects of ACH Processing with ease, including expectations, resubmissions, and inquiries; features five daily ACH submissions and the latest ACH deadline in the industry.
featuredFeatures:
  - title: Multiple Transfer Speeds 
    groupName: 
    description: Give customers multiple transfer speed options from Standard ACH, and Next Day, to Next Day Good Funds or Instant. Link Transfer ServicesFund Transfer.
    featured: true
    relatedDocs:
     - link: docs/fund-transfer/FT-freq.md
       title: 
    relatedAPIs:
      - type: post
        path: /reference/1.0.0/sample.yaml
        title: 
  - title: Real Time Speed using Instant Transfer
    groupName: Account Verification
    description: NOW® Network from Fiserv lets your accountholders transfer money between two instant-enabled accounts at different financial institutions in real-time or by the next day. This removes the credit risk related to ACH-based, next-day services. Link Instant Transfers (Via the NOW Network).
    featured: true
    relatedDocs:
     - link: docs/acc-to-acc-transfer/Account-Verify/Instant-Verify.md
       title: Instant Verification
    relatedAPIs:
      - type: post
        path: /reference/1.0.0/sample.yaml
        title: 
  - title: Multiple Account Verification
    groupName: Manage Account
    description: "Leverage Commerce Hub's Apple Tap to Pay SDK to accept in-store payments on mobile devices."
    featured: true
    relatedDocs:
     - link: docs/acc-to-acc-transfer/Manage-Account/acc-verify-home.md
       title: Account Verification
    relatedAPIs:
      - type: post
        path: /reference/1.0.0/sample.yaml
        title: 
  - title: Responsive Web Design 
    groupName: Responsive Web Design
    description: Having an interactive, innovative website is key to meeting customer expectations and keeping them interested in your brand. With Web Design Services, Fiserv offers flexible, responsive design for financial institutions delivering outstanding results for desktop, tablet and mobile users, ensuring a consistent brand experience across all devices. Benefits of our services include more mobile traffic, lower maintenance needs, faster webpages and an overall improved online experience.
    featured: false
    relatedDocs:
     - link: docs/resp-webdesign.md
       title: Responsive Web Design
    relatedAPIs:
      - type: post
        path: /reference/1.0.0/sample.yaml
        title:
  - title: Industry-Leading Security
    groupName: Industry-Leading Security
    description: Leverage Fiserv best -of-breed, powerful risk management tools.
    featured: false
    relatedDocs:
     - link: /docs/getting-started.md
       title: Industry-Leading Security
    relatedAPIs:
      - type: post
        path: /payments/v1/charges
        title:
